// Настоящий API, кейс и временные сохранённые отчёты. Подменены только ошибки/задержки/пустой набор.
async (page, base) => {
  let checks=0;
  const errors=[];
  const check=(value,message)=>{if(!value)throw new Error(message);checks++;console.log(`OK ${checks}: ${message}`);};
  page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:1440,height:900});
  await page.goto(base+'/anomalies');
  const rows=page.getByTestId('anomaly-field'), source=page.getByRole('group',{name:'Источник полей'});
  const year=page.getByLabel('Сезон отклонений'), search=page.getByLabel('Название или номер поля');
  const loaded=()=>page.locator('.anomaly-list[aria-busy="false"]').waitFor();
  const switchSource=async(label,value)=>{
    await source.getByRole('button',{name:label,exact:true}).click();
    await page.waitForURL(url=>url.searchParams.get('source')===value);
    await page.waitForFunction(label=>document.querySelector('.anomaly-sources button[aria-pressed="true"]')?.textContent===label,label);
  };
  await loaded();
  check(await source.getByRole('button',{name:'Мои поля',exact:true}).getAttribute('aria-pressed')==='true','Свои поля по умолчанию');
  const saved=await (await page.request.get(base+'/api/user-polygons')).json();
  check(saved.length===3 && await rows.count()===3,'Тот же набор, что у новых территорий; без дублей');
  check(await year.inputValue()==='2025','Последний доступный сезон');
  const south=rows.filter({hasText:'Южное'}), north=rows.filter({hasText:'Северное'}), river=rows.filter({hasText:'У реки'});
  check(await south.getAttribute('data-level')==='clear','Поле без эпизодов остаётся в списке');
  check(await north.getAttribute('data-level')==='unknown','Нет сезона не считается нормой');
  check(await river.getAttribute('data-level')==='data','Ошибка снимка отделена от угнетения');
  check(await page.locator('.year-bars, table.rows').count()===0,'Убраны график лет и перегруженная таблица');
  await year.selectOption('2024');await loaded();
  await south.locator('.anomaly-row').click();
  check(await south.getByRole('group',{name:'Период отклонения'}).getByRole('button').count()===2,'Два эпизода внутри поля');
  check(await south.getByText(/Zmin:/).isVisible()===false,'Числа скрыты');
  await south.getByRole('group',{name:'Период отклонения'}).getByRole('button').nth(1).click();
  const link=south.getByRole('link',{name:'Показать период на графике'});
  check((await link.getAttribute('href')).includes('from=2024-08-01'),'Переход для выбранного эпизода');
  await link.click();
  await page.getByTestId('season-panel').waitFor();
  check(await page.getByTestId('season-panel').getAttribute('data-year')==='2024','Открывается исторический сезон своего поля');
  await page.waitForFunction(()=>{
    const chart=document.querySelector('[data-testid="ndvi-chart"]');
    return chart && new Date(Number(chart.dataset.from)).getMonth()===6;
  });
  check(true,'График приближен к выбранному периоду');
  await page.goBack();await loaded();
  check(await year.inputValue()==='2024','Назад сохраняет сезон');
  await search.fill('юЖн');
  check(await rows.count()===1,'Поиск по имени без учёта регистра');
  await search.fill('');
  await page.locator('.anomaly-filters summary').click();
  await page.getByLabel('Тип отклонения').selectOption('high');
  check(await rows.count()===1,'Фильтр сильных отклонений');
  await page.getByLabel('Тип отклонения').selectOption('all');
  await page.locator('.anomaly-filters summary').click();
  await switchSource('Поля кейса','case');await loaded();
  check(await rows.first().getAttribute('data-source')==='case','Кейс отдельно');
  await search.fill('AOI-0001');check(await rows.count()===1,'Поиск по номеру');await search.fill('');
  await switchSource('Все','all');await loaded();
  await search.fill('Южное');check(await rows.count()===1,'Свои поля в общем списке');await search.fill('');
  await page.route('**/api/anomaly-fields?source=mine',route=>route.fulfill({status:503,contentType:'application/json',body:'{"detail":"Тестовая ошибка"}'}));
  await switchSource('Мои поля','mine');
  await page.getByText('Тестовая ошибка',{exact:true}).waitFor();
  await page.unroute('**/api/anomaly-fields?source=mine');
  await page.getByRole('button',{name:'Повторить загрузку'}).click();await loaded();
  await page.waitForFunction(()=>document.querySelectorAll('[data-testid="anomaly-field"]').length===3);
  check(await rows.count()===3,'Повтор после ошибки');
  await page.route('**/api/anomaly-fields?source=case',async route=>{const r=await route.fetch();await new Promise(r=>setTimeout(r,1200));await route.fulfill({response:r});});
  await switchSource('Поля кейса','case');
  await switchSource('Мои поля','mine');await loaded();await page.waitForTimeout(1400);
  check(await rows.count()===3 && await rows.first().getAttribute('data-source')==='mine','Поздний ответ не меняет источник');
  await page.unrouteAll({behavior:'ignoreErrors'});
  await page.screenshot({path:'artifacts/e2e/anomalies-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  await river.locator('.anomaly-row').click();
  check(await river.getByText('Что проверить',{exact:true}).isVisible(),'Раскрытие на телефоне');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Нет горизонтального скролла');
  await page.screenshot({path:'artifacts/e2e/anomalies-mobile.png'});
  await page.route('**/api/anomaly-fields?source=mine',route=>route.fulfill({status:200,contentType:'application/json',body:'{"years":[],"year":null,"fields":[]}'}));
  await page.reload();await loaded();
  await page.getByRole('link',{name:'Добавить поле в новой территории'}).waitFor();
  check(await rows.count()===0,'Пустой набор с переходом к добавлению');
  check(errors.length===0,`Нет ошибок JS: ${errors.join('; ')}`);
  return {checks,errors};
}
