// Браузер → настоящий FastAPI → локальный Nominatim. Проверяем фактическую рамку WebGL-карты.
async (page, base = "http://127.0.0.1:8011") => {
  let checks = 0;
  const check = (value, message) => { checks++; if (!value) throw new Error(message); console.log(`OK ${checks}: ${message}`); };
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`${base}/explore`);
  const map = page.getByTestId("field-map");
  await page.locator('[data-testid="field-map"][data-state="ready"]').waitFor();
  const input = page.getByLabel("Найти место", { exact: true });
  const button = page.getByRole("button", { name: "Найти", exact: true });
  const status = page.locator(".place-search-feedback");
  const results = page.locator(".place-results button");
  const search = async text => {
    await input.fill(text);
    const response = page.waitForResponse(r => r.url().includes("/api/places?"));
    await input.press("Enter");
    return response;
  };
  const bounds = async () => (await map.getAttribute("data-bounds")).split(",").map(Number);
  const centered = async (lon, lat) => page.waitForFunction(({ lon, lat }) => {
    const [w, s, e, n] = document.querySelector('[data-testid="field-map"]').dataset.bounds.split(",").map(Number);
    return Math.abs((w + e) / 2 - lon) < .02 && Math.abs((s + n) / 2 - lat) < .02;
  }, { lon, lat });
  check(await button.isDisabled(), "Пустой запрос запрещён");
  let requests = 0;
  page.on("request", req => { if (req.url().includes("/api/places?")) requests++; });
  await input.fill("Ростов, Большая Садовая");
  await page.waitForTimeout(350);
  check(requests === 0, "Нет запросов при наборе");
  const first = await search("Ростов, Большая Садовая");
  check(first.ok(), "Поиск через бэкенд");
  const payload = await first.json();
  await results.first().waitFor();
  check(await results.count() === 2, "Выбор из неоднозначных мест");
  check((await results.first().innerText()) === payload[0].label, "Адрес взят из API");
  await results.first().click();
  await centered(39.72, 47.22);
  let box = await bounds();
  check(box[2] - box[0] < .2, "Улица приближена");
  check((await status.innerText()).includes("На карте:"), "Выбранное место показано");
  await search("Ростов, Большая Садовая");
  await results.nth(1).click();
  await page.waitForFunction(() => {
    const b = document.querySelector('[data-testid="field-map"]').dataset.bounds.split(",").map(Number);
    return b[0] <= 38.22 && b[2] >= 44.33 && b[1] <= 45.95 && b[3] >= 50.22;
  });
  check(true, "Область целиком входит в карту");
  await search("45.0355, 38.9753");
  await results.first().click();
  await centered(38.9753, 45.0355);
  await page.waitForFunction(() => {
    const b = document.querySelector('[data-testid="field-map"]').dataset.bounds.split(",").map(Number);
    return b[2] - b[0] < .1;
  });
  check((await bounds())[2] - (await bounds())[0] < .1, "Координаты приближены");
  await page.getByRole("button", { name: "Нарисовать контур вручную" }).click();
  const canvas = await map.boundingBox();
  await page.mouse.click(canvas.x + canvas.width * .4, canvas.y + canvas.height * .60);
  await page.mouse.click(canvas.x + canvas.width * .65, canvas.y + canvas.height * .60);
  await page.mouse.dblclick(canvas.x + canvas.width * .55, canvas.y + canvas.height * .78);
  await page.getByText(/Контур задан, около/).waitFor();
  check(true, "После поиска можно нарисовать поле");
  await page.waitForTimeout(1200);
  await search("Несуществующее место");
  await page.getByText(/Ничего не найдено/).waitFor();
  check(await results.count() === 0, "Пустой ответ удаляет результаты");
  await page.waitForTimeout(1200);
  const failed = await search("Ошибка источника");
  check(failed.status() === 502, "Ошибка внешнего сервиса проходит через API");
  await page.getByText(/Поиск адресов временно недоступен/).waitFor();
  await page.waitForTimeout(1200);
  check((await search("Ошибка источника")).ok(), "Повтор после ошибки успешен");
  await results.first().waitFor();
  await page.waitForTimeout(1200);
  await input.fill("Медленный ответ");
  await button.click();
  await page.getByText("Ищем место…", { exact: true }).waitFor();
  await input.fill("Новый текст");
  await page.waitForTimeout(2300);
  check(await results.count() === 0 && await status.innerText() === "", "Запоздалый ответ не меняет новый запрос");
  check((await search("91, 30")).status() === 400, "Неверные координаты отклонены");
  await page.setViewportSize({ width: 390, height: 844 });
  await search("45.0355, 38.9753");
  await results.first().click();
  await centered(38.9753, 45.0355);
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "Нет горизонтального скролла на телефоне");
  check(await button.isVisible(), "Поиск доступен на телефоне");
  await page.screenshot({ path: "artifacts/e2e/geocoding-mobile.png", timeout: 10000 });
  await page.getByRole("button", { name: "Очистить поиск" }).click();
  check(await input.inputValue() === "" && await button.isDisabled(), "Очистка поиска");
  check(errors.length === 0, `Ошибки JS: ${errors.join("; ")}`);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: "artifacts/e2e/geocoding-desktop.png", timeout: 10000 });
  return { checks, errors };
}
