import pandas as pd, numpy as np
pd.set_option('display.width', 250); pd.set_option('display.max_columns', 50); pd.set_option('display.max_rows', 200)
tr = pd.read_csv('data/train_dataset.csv', parse_dates=['date'])
te = pd.read_csv('data/test_dataset.csv', parse_dates=['date'])
for name, df in [('TRAIN', tr), ('TEST', te)]:
    print('='*30, name, df.shape)
    print(df.dtypes)
    print('\nNaN share:'); print((df.isna().mean()*100).round(2))
    print('\nPolygons:', df.anon_polygon_id.nunique(), ' dates:', df.date.min().date(), '->', df.date.max().date(), ' unique dates:', df.date.nunique())
    print('years:', sorted(df.year.dropna().unique().astype(int)))
    print('crop_type:\n', df.crop_type.value_counts(dropna=False))
    print('dup key rows:', df.duplicated(['anon_polygon_id','date']).sum())
    print('rows per polygon:\n', df.groupby('anon_polygon_id').size().describe())
    print('\ndescribe:\n', df.describe().T)
print('\nOverlap polygons train/test:', len(set(tr.anon_polygon_id)&set(te.anon_polygon_id)))
print('train polys:', sorted(tr.anon_polygon_id.unique()))
print('test polys:', sorted(te.anon_polygon_id.unique()))
print('\nTRAIN status:\n', tr.status.value_counts(dropna=False))
print('\nTEST is_synthetic_gap:\n', te.is_synthetic_gap.value_counts(dropna=False))
